services:
  - type: web
    name: mineradio
    env: docker
    region: singapore
    plan: free
    branch: master
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: MINERADIO_BEAT_CACHE_DIR
        value: /tmp/beatmaps
